import { PGClient } from '@linked-db/linked-ql/postgres';

const db = new PGClient();

export async function setup() {
    await db.connect();

    try {
        // 1. Create the table
        await db.query(`
            CREATE TABLE test_todos (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL,
                done BOOLEAN DEFAULT false
            );
        `);

        // 2. Populate with 4 rows
        const query = `INSERT INTO test_todos (title, done) VALUES ($1, $2)`;
        const todos = [
            ['Invent a better fetch()', true],
            ['Explain LiveResponse without saying "WebSocket"', false],
            ['Fix bug that disappears when console.log is added', false],
            ['Refactor code that was "temporary" 6 months ago', true],
        ];

        for (const todo of todos) {
            await db.query(query, todo);
        }

        console.log("Table created and 4 todos inserted.");
    } catch (err) {
    }
}

// Cleanup function
export async function cleanup() {
    console.log("\nCleaning up database...");
    try {
        await db.query('DROP TABLE IF EXISTS test_todos CASCADE;');
        console.log("Table 'test_todos' dropped.");
    } catch (err) {
        console.error("Error during database cleanup:", err);
    } finally {
        await db.disconnect();
        process.exit();
    }
};